[versions]
minecraft = "1.21.1"
parchment-minecraft = "1.21.1"
parchment-mappings = "2024.11.17"

architectury = "13.0.8"

fabric-loader = "0.16.9"
fabric-api = "0.116.7+1.21.1"

fabric-forgeConfigPort = "21.1.6"

neoforge-platform = "21.1.219"
neoforge-loader = "4"

[plugins]
loom = { id = "dev.architectury.loom", version = "1.13-SNAPSHOT" }
architectury = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
architectury-api = { group = "dev.architectury", name = "architectury", version.ref = "architectury" }

# Fabric
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-architectury = { group = "dev.architectury", name = "architectury-fabric", version.ref = "architectury" }

fabric-forgeConfigPort = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "fabric-forgeConfigPort" }
fabric-energy = { group = "teamreborn", name = "energy", version = "4.1.0" }

# NeoForge
neoforge-platform = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge-platform" }
neoforge-architectury = { group = "dev.architectury", name = "architectury-neoforge", version.ref = "architectury" }
